name: fmippn_dbzhtorate
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.7
  - numpy
  - pyproj
  - git
  - h5py
  - pip
  - pysteps=1.18.1
  - opencv
  - pandas
  - numba
  - dask
  - bottleneck
  - pip:
      - git+https://github.com/fmidev/hiisi.git@string-types
