name: fmippn_dbzhtorate
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pyproj
  - git
  - h5py
  - pip
  - pysteps
  - opencv
  - pandas
  - numba
  - dask
  - pip:
      - git+https://github.com/karjaljo/hiisi.git
